   version: '3.8'
   services:
     devcontainer:
       image: mcr.microsoft.com/vscode/devcontainers/python:3.9
       platform: linux/arm64/v8
       volumes:
         - ..:/workspaces/${localWorkspaceFolderBasename}
       environment:
         - LOCAL_WORKSPACE_FOLDER=/workspaces/${localWorkspaceFolderBasename}
       ports:
         - "3000:3000" # Adjust ports as needed
       # Add any additional configurations if necessary
